{% set name = "adorn" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adorn-{{ version }}.tar.gz
  sha256: 853064087377c5b997755eb8cb01336dd97a11b246ecf3d615aaa439d0cfe526

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.1,<2.0
  run:
    - python >={{ python_min }},<4.0
    - pyyaml >=6.0.0,<7.0.0
    - tomli >=2.0.1,<3.0.0

test:
  imports:
    - adorn
    - adorn.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyadorn/adorn
  summary: Adorn
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jameswinegar
    - jacobBaumbach
